apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels: { app: python-api }
  template:
    metadata:
      labels: { app: python-api }
    spec:
      containers:
        - name: python-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://appuser:apppass@pg-postgresql.data.svc.cluster.local:5432/appdb"
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  selector: { app: python-api }
  ports:
    - port: 80
      targetPort: 8000
