services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
  python-api:
    build: ./apps/python-api
    environment:
      DATABASE_URL: postgresql://appuser:apppass@postgres:5432/appdb
    depends_on: [postgres]
    ports:
      - "8000:8000"
  java-api:
    build: ./apps/java-api
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/appdb
      DB_USER: appuser
      DB_PASS: apppass
    depends_on: [postgres]
    ports:
      - "8080:8080"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [node-exporter]
